### ISSUE TITLE
Conditional next/prev links

### ISSUE THREAD

**Issue by tssp** [paylogic/halogen#19]
When implementing collection endpoints with paging support, the `_link` relations usually have `next` and `prev` links. A corresponding schema for a `user` collection could be something like

```
class UserCollectionSchema(Schema):

  self = halogen.Link(attr=lambda u: f"url?page={u.page}")
  next = halogen.Link(attr=lambda u: f"url?page={u.page + 1}")
  prev = halogen.Link(attr=lambda u: f"url?page={u.page - 1}")

  users = halogen.Embedded(halogen.types.List(UserSchema), attr=...)
```

Is it possible to only serialize/render the `next` and `prev` links only when a certain condition is met, e.g. when there is actually a next or a previous page?

**Comment by olegpidsadnyi** [comment]
We do it differently, but since the decorator way was introduced you could try something like this:

```python

class UserCollectionSchema(Schema):

    self = halogen.Link(attr=lambda u: f"url?page={u.page}")
    @halogen.Link(required=False)
    def next(u):
        if not u.next_page_url:
           raise AttributeError()
       return u.next_page_url
       
```

Once the attr is not required it will be dropped on AttrbuteError

**Comment by tssp** [comment]
Thanks, this is exactly what I was looking for.
